# Generated by Django 5.2.3 on 2026-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_plant',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='humidity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='pot_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sunlight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='water',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
