# Generated by Django 5.2.3 on 2026-04-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_about_plant_product_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='humidity',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Normal room humidity', 'Normal room humidity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Indirect sunlight', 'Indirect sunlight')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='water',
            field=models.CharField(blank=True, choices=[('Once a week', 'Once a week'), ('Twice a week', 'Twice a week'), ('Keep soil moist', 'Keep soil moist'), ('Low water requirement', 'Low water requirement')], max_length=50),
        ),
    ]
