# Generated by Django 5.2.3 on 2026-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_difficulty_alter_product_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='difficulty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='humidity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sunlight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='water',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
