# Generated by Django 5.2.3 on 2026-04-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_difficulty_alter_product_humidity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='about_plant',
            new_name='about_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pot_included',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sunlight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='water',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='return_policy',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='whats_included',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CareProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.TextField(blank=True)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_spec', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='PlantSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunlight', models.CharField(blank=True, max_length=50)),
                ('water', models.CharField(blank=True, max_length=50)),
                ('humidity', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=50)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('pot_included', models.BooleanField(default=True)),
                ('air_purifying', models.BooleanField(default=False)),
                ('low_maintenance', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plant_spec', to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='PotSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('drainage', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pot_spec', to='store.product')),
            ],
        ),
    ]
