# Generated by Django 5.2.3 on 2026-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productfaq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor Plants'), ('outdoor', 'Outdoor Plants'), ('care', 'Plant Care'), ('tips', 'Gardening Tips'), ('services', 'Garden Services')], default='tips', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
