# Generated by Django 5.2.3 on 2026-04-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_has_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_in_search',
            field=models.BooleanField(default=False),
        ),
    ]
